import js from "@eslint/js";
import eslintPluginPrettier from "eslint-plugin-prettier/recommended";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import tseslint from "typescript-eslint";

export default tseslint.config(
  {
    // .claude holds git worktrees other tooling sessions create, which are full
    // copies of this repository — linted, every error appeared twice with a
    // path nobody can act on. .nitro is build output like .output.
    ignores: ["dist", ".output", ".vinxi", ".nitro", ".claude"],
  },
  {
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    files: ["**/*.{ts,tsx}"],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
    },
    plugins: {
      "react-hooks": reactHooks,
      "react-refresh": reactRefresh,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      "no-restricted-imports": [
        "error",
        {
          paths: [
            {
              name: "server-only",
              message:
                "TanStack Start does not use the Next.js `server-only` package. Rename the module to `*.server.ts` or mark it with `@tanstack/react-start/server-only`.",
            },
          ],
        },
      ],
      "react-refresh/only-export-components": ["warn", { allowConstantExport: true }],
      "@typescript-eslint/no-unused-vars": "off",
    },
  },
  eslintPluginPrettier,

  /*
    The Supabase functions run on Deno, and Deno lints them.

    They are not part of the app build: they import by URL, use Deno globals,
    and carry deno-lint-ignore directives for the places where a provider's wire
    format genuinely is dynamic. Running this config's type rules over them as
    well means every such place needs two suppressions on one line, which
    Prettier then reflows apart — so the second one silently stops applying.

    Formatting still applies, because one house style across the repository is
    worth having. Only the type rules step back.
  */
  {
    files: ["supabase/functions/**/*.ts"],
    rules: { "@typescript-eslint/no-explicit-any": "off" },
  },

  /*
    shadcn/ui components export their variants beside themselves.

    buttonVariants, badgeVariants, useFormField, useSidebar — co-exporting these
    is upstream's own convention, and these files are generated by the shadcn
    CLI. Splitting them would mean every component added or updated later
    reintroduces the warning and has to be split again by hand, so the divergence
    would have to be maintained forever to satisfy a rule about hot-reload
    granularity in development.

    The app's own components were fixed properly rather than exempted: the
    helpers they exported are now in src/lib, where a date function or a
    selector belongs anyway.
  */
  {
    files: ["src/components/ui/**/*.tsx"],
    rules: { "react-refresh/only-export-components": "off" },
  },
);
